import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client'

import '../styles/globals.css'

const client = new ApolloClient({
  uri: 'https://api.github.com/graphql',
  headers: {
    Authorization: `bearer ${process.env.NEXT_PUBLIC_GITHUB_TOKEN}` || '',
  },
  ssrMode: typeof window === 'undefined',
  cache: new InMemoryCache(),
})
function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Apollo Client Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApolloProvider client={client}>
        <Component {...pageProps} />
      </ApolloProvider>
    </>
  )
}

export default MyApp
